// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Claim struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Role struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type RoleClaim struct {
	RoleID  int32 `json:"roleId"`
	ClaimID int32 `json:"claimId"`
}

type Task struct {
	ID          int32       `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	CreatedBy   int32       `json:"createdBy"`
	AssignedTo  int32       `json:"assignedTo"`
	CreatedAt   time.Time   `json:"createdAt"`
	AssignedAt  time.Time   `json:"assignedAt"`
	DueDate     time.Time   `json:"dueDate"`
	Status      int8        `json:"status"`
}

type Team struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedBy   int32       `json:"createdBy"`
	CreatedAt   time.Time   `json:"createdAt"`
}

type TeamMember struct {
	TeamID   int32     `json:"teamId"`
	UserID   int32     `json:"userId"`
	JoinedAt time.Time `json:"joinedAt"`
}

type User struct {
	ID                int32     `json:"id"`
	FirstName         string    `json:"firstName"`
	LastName          string    `json:"lastName"`
	Email             string    `json:"email"`
	IsEmailVerified   bool      `json:"isEmailVerified"`
	PasswordHash      string    `json:"passwordHash"`
	ProfilePictureUrl string    `json:"profilePictureUrl"`
	CreatedAt         time.Time `json:"createdAt"`
}

type UserRole struct {
	UserID     int32     `json:"userId"`
	RoleID     int32     `json:"roleId"`
	AssignedAt time.Time `json:"assignedAt"`
}

type UserTask struct {
	UserID     int32     `json:"userId"`
	TaskID     int32     `json:"taskId"`
	AssignedAt time.Time `json:"assignedAt"`
}
